### ISSUE TITLE
Document Helm Deploy/Upgrade for MinIO Operator

### ISSUE THREAD

**Issue by ravindk89** [minio/docs#1021]
**Summary**

We have a growing userbase relying on the MinIO Operator Helm Charts for deployment.
As part of supporting that, we need to bring in the Helm-based deploy/upgrade process to the web docs.

A few collected notes:

- Clusters using helm for tenant management should **not** use the `kubectl minio` CLI, as it can result in condition/race issues that conflict with chart-based management tools (ArgoCD)

**Goals**

List the in-scope goals

- [ ] Add Deploy/Manage/Upgrade/Delete tutorials based on Helm
- [ ] Create a Helm chart reference
- [ ]

**Non-Goals**
- [ ] Complete reference of values.yaml
- [ ] A discussion of how Helm charts work
- [ ] A discussion of the community helm chart

List any items that are out of scope

**Additional context**

**Comment by cniackz** [comment]
Adding more information, when using ArgoCD with Helm, you don't have to use minio plugin for k8s because it is a racing condition between ArgoCD and the plugin itself. If for instance you need to upgrade the minio image, all you have to do is change the tenant chart on your Git repository and then Synch via ArgoCD.
