### ISSUE TITLE
Many steps are not applicable for macos MNMD installation.

### ISSUE THREAD

**Issue by jingsam** [minio/docs#1084]
**Describe the bug**
I notice the [macos MNMD installation guide](https://min.io/docs/minio/macos/operations/install-deploy-manage/deploy-minio-multi-node-multi-drive.html) contains many linux specific steps, such as firewalld, fstab, systemd, which are not applicable to macos.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ravindk89** [comment]
IMHO We can drop OSX down to just SNSD and SNMD, the latter of which I'm not even sure makes sense as there are limited modern builds available that support multi-drive layouts anyways.

**Comment by ravindk89** [comment]
@harshavardhana might need an assist here.

- https://min.io/docs/minio/macos/operations/install-deploy-manage/deploy-minio-multi-node-multi-drive.html

Compare to staging:

- http://192.241.195.202:9000/staging/DOCS-1084/macos/operations/installation.html

File exists on the remote server. *BUT* when building locally via `build-docs.sh`, it does *not* show up.

It's odd because other docs have been updated, so the `build-docs.sh` script is firing on commit. But it seems like maybe the `macos` folder isn't getting cleared in `/var/www/docs/minio/macos` - possibly a permissions issue? It should be executing as root though so IDK why it would be an issue.
