### ISSUE TITLE
Wildcard TLS Certificates Require Binding Hostname to --addr

### ISSUE THREAD

**Issue by ravindk89** [minio/docs#358]
# Summary

Related to https://github.com/minio/minio/issues/12651 and https://github.com/minio/minio/issues/12646#issuecomment-876610382 , if using a custom TLS certificate with wildcard DNS *and* no IP SAN, MinIO Console throws login errors due to some TLS issues.

The solution here is to set `--addr HOSTNAME:PORT` where `HOSTNAME` resolves to the MinIO deployment *and* is covered by the wildcard certificate.

# Goals

Update the TLS documentation to make note of this requirement. 

# Non-Goals

Additional fixes to TLS documentation.

**Comment by cs3gallery** [comment]
Can we make sure we put better clarification about doing this with clusters? I have the same issue but am launching in a cluster mode with the domain info without using the --addr flag such as : `https://minio{1...4}.contoso.com/data{1...4}/data`

Does this mean we need to add something like this on each node? : 
`--addr minio1.contoso.com:443 https://minio{1...4}.contoso.com/data{1...4}/data` on node 1
`--addr minio2.contoso.com:443 https://minio{1...4}.contoso.com/data{1...4}/data` on node 2 etc.

Or... since I am using a reverse proxy would I use the reverse proxy domain name in those such as:
'--addr s3.contoso.com:443 https://minio{1...4}.contoso.com/data{1...4}/data' on all the nodes?

Thanks.. just a bit of clarification :)

**Comment by ravindk89** [comment]
So I'm holding this work because of some upcoming updates that might further refine the solution here. Specifically https://github.com/minio/minio/pull/12770

@harshavardhana correct me if I'm wrong, but with the next release, for situations like the above, users can set `MINIO_SERVER_URL` to *any* hostname that resolves to the MinIO deployment (and covered by the TLS certificate) ?

**Comment by harshavardhana** [comment]
> @harshavardhana correct me if I'm wrong, but with the next release, for situations like the above, users can set `MINIO_SERVER_URL` to _any_ hostname that resolves to the MinIO deployment (and covered by the TLS certificate) ?

We have already made the release where MINIO_SERVER_URL is now available

**Comment by ravindk89** [comment]
This *might* be gone away with the changes to how Console communicates with MinIO. Or it might be worse - we have to do a lot of testing to understand how this specific case would work.

For now, backlog as the majority of our TLS issues are K8s-related, and we need to prioritize that research.

**Comment by feorlen** [comment]
I was not able to reproduce this. The consensus is enough has changed in 2+ years that this is no longer a concern. If it comes up again, we can revisit.
