### ISSUE TITLE
Update Docker/Podman FS/Migration Guide to use container-specific procedure instead of generic

### ISSUE THREAD

**Issue by ell1e** [minio/docs#660]
The disk migration error prompting now after a release links to this docs page: https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html which links me to here for making a new deployment: https://min.io/docs/minio/linux/operations/install-deploy-manage/deploy-minio-single-node-single-drive.html#deploy-minio-standalone

This is a docker image. You really want me to mess around with systemd units in a docker image? I'm assuming not and the entire guide is just unsuitable for the (official) docker image, but then the docker image really should link a guide in this error message in the log that is suitable for it instead.

## Expected Behavior
Guide linked as startup error from docker image actually is applicable to docker image

## Current Behavior
Guide linked as startup error from docker image seems to only talk about things you'd do on a standalone system-wide install and not in a container

## Possible Solution
Link an applicable guide instead

## Steps to Reproduce (for bugs)
1. Migrate old docker image to new
2. Get error `minio_1      | ERROR Unable to use the drive /data: Drive /data: found backend type fs, expected xl or xl-single - to migrate to a supported backend visit https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html: Invalid arguments specified`
3. Click URL.

## Context
Currently, my website is down and I'm not sure how to migrate. I'll probably go back to old minio until I can actually get proper instructions on what I'm even supposed to be doing.

## Regression
Yes, regression or rather migration issue

## Your Environment

* Version used (`minio --version`): latest `minio/minio` docker image
* Server setup and configuration: Alpine Linux on the host, docker image uses `/data` volume mounted in and startup command `server /data` which used to work. The above error is entirely unhelpful in telling me what would now work.
* Operating System and version (`uname -a`): Alpine Linux 3.17 with docker 20.10.21 (no kubernetes or anything fancy)

**Comment by harshavardhana** [comment]
We can add instructions for docker @djwfyi @ravindk89

**Comment by ravindk89** [comment]
The container docs generally need another overall pass for updates. We simply are bouncing between various priorities, and updating this particular page fell out of the high priority queue.

I'll take a look this week while I'm also digging into the K8s platform work.

**Comment by ravindk89** [comment]
I'll note - MinIO doesn't *know* it's in a container. So updating our docs isn't going to change what that output link will be, at least right now. @harshavardhana I think we already have some logic for attempting to detect these kinds of details, not sure if we can leverage those to selectively dictate which URLs to output to users when linking out to docs.

That said, the only difference there's going to be here is that instead of spinning up a new MinIO deployment via systemd, for containers you'd create a new container with the updated binary, migrate your data over, shut down your old container, and then restart the new container with the necessary hostnames, etc. The new container would really just need a different port number in the short term. 

That's it - the steps otherwise should be the same @ell1e . I'm working through these clean ups this and next week, but you are welcome to slightly modify the steps in that way to move forward.

**Comment by ell1e** [comment]
But what does "migrate the data" mean? The docs act like it's some extremely different type of storage that is no longer in the filesystem, but the docker container still instructs me to do *a plain filesystem mount.* This is why I'm confused, if a mount still works, then why can't the container just auto-migrate? If a mount doesn't work anymore and I need some sort of special volume, then the container instructions seem wrong.

(As for detecting the container, you could just set an env var in the Dockerfile that minio checks.)

**Comment by Smasherr** [comment]
I'm in the same boat and don't really know how to migrate my docker-based MinIO installation.

**Comment by ell1e** [comment]
If I'm reading this right, you just made a new container but with the essentially same configuration, and just fed the old data in the new one? Basically just the internal storage format changed and that's the only reason for this slight mess?

So why isn't the new container just migrating this in-place on startup? This is what the vast majority of docker containers do. If no config changes are needed anyway, why have users do this whole two containers dance?

**Comment by Smasherr** [comment]
I'm not the right person to answer this question (I'm just a user), but for instance, if you think of a major version upgrade of a database, you don't get the migration for free as well.

**Comment by ell1e** [comment]
> you don't get the migration for free as well.

That's not universally true. Something like GitLab always migrates. I think MariaDB also always migrates, but I could be wrong. There are some that don't, and I would advice admins relying on containers to avoid them because it's usually not worth the hassle.

**Comment by Smasherr** [comment]
To be more specific, I had Postgres in my mind. I run a docker-based installation of Postgres and the official process of migration is [somewhat similar](https://www.postgresql.org/docs/15/pgupgrade.html) to what I did with MinIO. Fortunately enough, there is a [third-party helper](https://github.com/tianon/docker-postgres-upgrade) for that.

**Comment by ravindk89** [comment]
So a few things:

- I realized that we have a snippet [here](https://min.io/docs/minio/linux/operations/install-deploy-manage/deploy-minio-single-node-single-drive.html) that better describes (I think) the fact that the backend data format has changed from FS -> Erasure Coding, and there is no built-in tool for migrating from one to the other. Having this on the FS migration page might help users who want to know more about what is changing. The TL;DR is that erasure coded objects cannot be accessed on disk in the same way as FS mode - you have to go through MinIO to 'decode' the objects.

- @Smasherr basically nailed the procedure - start up a new MinIO container, use `mc mirror` or `mc cp` to copy data, copy over any other policies, configs, etc., then tear down the old and start up the new. The main bugbears are going to be for systems where your original setup is using the root of the storage volume, in which case you'll probably have to move that entire chunk of data to a subdirectory. or if your root device is already more than half full, in which case migration might get dicey since it's not a "move", it's a "copy". 

- A part of why we don't auto-migrate is because it's irreversible. There are users who have very specific interactions with the FS mode that no longer work with the erasure coding backend. It's better for us to error out and have the user examine their stack and ensure it is ready to migrate to the S3 API then to migrate and leave users with the job of now catching their stack up. Engineering has indicated that we are not supporting FS mode nor that backend any longer, so it's unlikely they would take on a request to allow for "flipping" back and forth at the critical version for any given reason.

- If you have specific questions, comments, or suggestions about how MinIO should run, please make those on github.com/minio/minio. This repository is only for documentation.

I'll also leave a reminder that MinIO is an open source project, and any user who feels strongly about a feature is welcome to try building it out themselves. Otherwise, you have to respect our Engineer's decision if they indicate they have no time or interest in implementing a given request.

**Comment by ell1e** [comment]
> , so it's unlikely they would take on a request to allow for "flipping" back and forth at the critical version for any given reason.

That wasn't what I suggested however, at all. I think a good solution would be to write a script for migration that comes with an old minio binary that can be manually prompted and does it in-place, and then change  the error message to indicating how to run it.

This retains all that you listed above, it remains irreversible, it doesn't need flipping back and forth, it keeps the error and makes sure the admin needs to do manual review on how to proceed, but it removes the huge time waste of setting up two containers and figure out the networking and everything for those just to do a migration.

**Comment by ravindk89** [comment]
> If you have specific questions, comments, or suggestions about how MinIO should run, please make those on https://github.com/minio/minio. This repository is only for documentation. If the conversation cannot stay on the topic of how to improve this specific tutorial, I'm going to lock it until I have the cycles to finish the corresponding PR.

**Comment by harshavardhana** [comment]
> I think a good solution would be to write a script for migration that comes with an old minio binary that can be manually prompted and does it in-place, and then change the error message to indicating how to run it.
> 
> This retains all that you listed above, it remains irreversible, it doesn't need flipping back and forth, it keeps the error and makes sure the admin needs to do manual review on how to proceed, but it removes the huge time waste of setting up two containers and figure out their networking and everything just to do a migration.

Good idea @ell1e happy to accept a PR on this.
