### ISSUE TITLE
Site failure recovery doesn't work as documented

### ISSUE THREAD

**Issue by hamalchristiaan** [minio/docs#677]
Site failure recovery requires 2 steps that don't work:
Step 3. Expand the existing site replication by adding the newly deployed site
Step 4. Remove the lost site from the site replication configuration

## Expected Behavior
Step 3. Expand the existing site replication by adding the newly deployed site:
expecting command 'mc admin replicate add siteA siteB siteC' to work

Step 4. Remove the lost site from the site replication configuration:
expecting command 'mc admin replicate remove siteA siteB --force' to work

## Current Behavior
'mc admin replicate add siteA siteB siteC' output: 
mc: <ERROR> Unable to add sites for replication. Error received when contacting a peer site (unable to create admin client for siteB/: Remote service endpoint https://siteB:9000 not available
remote target is offline for endpoint https://siteB:9000).

'mc admin replicate remove siteA siteB --force' output:
mc: <ERROR> Unable to remove cluster replication. Error received when contacting a peer site (unable to update peer siteB/: unable to create admin client for siteB/: Remote service endpoint https://siteB:9000/ not available
remote target is offline for endpoint https://siteB:9000/).

## Steps to Reproduce (for bugs)
1. Site replication active between site A and site B.
2. Crash Site B.
3. Create Site C as described in the first 2 steps of site failure recovery
4. Try 'mc admin replicate add siteA siteB siteC'
5. Try 'mc admin replicate remove siteA siteB --force'

## Your Environment
* Version used (`minio --version`): RELEASE.2022-12-12T19-27-27Z (commit-id=a469e6768df4d5d2cb340749fa58e4721a7dee96)
* Operating System and version (`uname -a`): Linux minio-repl02 5.10.0-15-amd64 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux

**Comment by hamalchristiaan** [comment]
Just to be clear, it's not only documentation.
Removing one site from another is not working ('mc admin replicate remove siteA siteB --force'). It tries to connect to the peer site, which isn't possible, and then it fails.

**Comment by harshavardhana** [comment]
> Removing one site from another is not working ('mc admin replicate remove siteA siteB --force'). It tries to connect to the peer site, which isn't possible, and then it fails.

@poornas ^^

**Comment by poornas** [comment]
@hamalchristiaan , you should be using `mc admin replicate remove --all --force sitea`, apologize for the oversight. Whether site is being added/removed from the site replication configuration, all sites need to be up for the operation to be successful. Otherwise a site that is temporarily down can have inconsistent setting and continue to think it is part of site replication. The only time this requirement can be relaxed is when entire cluster configuration is being removed.

@ravindk89 , can we update the docs - any time a site is being removed in this type of site failure situation, the entire site replication setup needs to be deconfigured with `mc admin replicate remove --all --force <sitea>` and then reconfigured with `mc admin replicate add` . The only time `mc admin replicate remove sitea siteb` can be used is when every site currently configured in site replication is up

**Comment by ravindk89** [comment]
@hamalchristiaan after some internal discussion, we'd prefer to fix the logic here to account for this.

Once we have improved the logic, we can clean up our documentation further. I'll patch it for now and include the note on the current behavior (just to get us past the post).

Appreciate you being engaged here.

**Comment by poornas** [comment]
Just a note - in this case @hamalchristiaan can still use `mc admin replicate remove --all --force` because there are only 2 sites in the site replication setup and one of them has to be replaced. If there are more than 2 sites, we will need to fix the logic to handle offline site

**Comment by ravindk89** [comment]
https://github.com/minio/docs/commit/54f1fa14da41f2a6d747dc179a49ee32c89398f5 at least corrects the procedure.

Technically it's still "wrong" in that you need --all, but I'd prefer to leave that out - any user who runs into an issue is someone we need to guide anyways, and once https://github.com/minio/minio/issues/16265 completes the docs would be correct.
