### ISSUE TITLE
Improve minio client installation step - add ARM64

### ISSUE THREAD

**Issue by hartraft** [minio/docs#679]
There are more installations of minio on ARM64/aarch64, updating the docs to reference the published ARM64 binary would help onboard new users / easier to copy/paste.

**Comment by ravindk89** [comment]
I'll consider this partial-complete as per #680 , but I think its worth mentioning our other builds on the Linux install-deploy-manage page - I can think of a few ways to do that without the section becoming unwieldy

**Comment by hartraft** [comment]
I have some armv7 devices on Linux that I manage so I can test those too next week.

Indeed having the whole matrix of configurations would be cluttered without tabbed pages or a "platform picker" or something. I can follow the lead on how you would like to have it organised

**Comment by ravindk89** [comment]
If you feel up to it - at least for now the format we're using for the MinIO Client page w/ the bolded sections would probably work fine. We just need to cover AMD64 vs ARM64 vs ARM - I don't think we need to worry about talking PPE or s390x builds right now.

As a warning from what I remember, we use a kinda weird single sourcing hierarchy for setting up those files. If you get lost feel free to ping here and I'll do what I can to help. Otherwise i should have time after the holidays do do a bit of cleanup.
